name: perpus_pram
version: 1.0.0+1
publish_to: none
description: Aplikasi perpustakaan untuk project UKK saya di SMK Negeri 5 Surakarta.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  dots_indicator: ^2.0.0
  date_time_picker: ^2.1.0
  intl: ^0.17.0
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_file: ^3.3.2
  fluttertoast: ^8.2.5
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/app/assets/icon/logoperpuspram.png"

flutter: 
  uses-material-design: true
  assets:
    - lib/app/assets/image/

